const movies = [
    { name: "Ramayana: The Legend of Prince Rama", genre: "Animation" },
    { name: "Rocketry: The Nambi Effect", genre: "Biography" },
    { name: "Nayakan", genre: "Crime" },
    { name: "Gol Maal", genre: "Comedy" },
    { name: "Anbe Sivam", genre: "Adventure" },
    { name: "777 Charlie", genre: "Adventure" },
    { name: "Pariyerum Perumal", genre: "Drama" },
    { name: "Manichithrathazhu", genre: "Comedy" },
    { name: "3 Idiots", genre: "Comedy" },
    { name: "The World of Apu", genre: "Drama" },
    { name: "Jai Bhim", genre: "Crime" },
    { name: "#Home", genre: "Drama" },
    { name: "Soorarai Pottru", genre: "Action" },
    { name: "Black Friday", genre: "Action" },
    { name: "Kumbalangi Nights", genre: "Comedy" },
    { name: "C/o Kancharapalem", genre: "Drama" },
    { name: "Kireedam", genre: "Action" },
    { name: "Like Stars on Earth", genre: "Drama" },
    { name: "Dangal", genre: "Action" },
    { name: "Jersey", genre: "Drama" },
    { name: "96", genre: "Drama" },
    { name: "Kaithi", genre: "Action" },
    { name: "Natsamrat", genre: "Drama" },
    { name: "Mayabazar", genre: "Comedy" },
    { name: "Sita Ramam", genre: "Action" },
    { name: "Drishyam 2", genre: "Crime" },
    { name: "Asuran", genre: "Action" },
    { name: "Thevar Magan", genre: "Drama" },
    { name: "Visaaranai", genre: "Crime" },
    { name: "Sarpatta Parambarai", genre: "Action" },
    { name: "Thalapathi", genre: "Action" },
    { name: "Nadodikkattu", genre: "Comedy" },
    { name: "Drishyam", genre: "Crime" },
    { name: "Thani Oruvan", genre: "Action" },
    { name: "Pather Panchali", genre: "Drama" },
    { name: "Jaane Bhi Do Yaaro", genre: "Comedy" },
    { name: "Vada Chennai", genre: "Action" },
    { name: "Aparajito", genre: "Drama" },
    { name: "Khosla Ka Ghosla!", genre: "Comedy" },
    { name: "Anniyan", genre: "Action" },
    { name: "Sardar Udham", genre: "Biography" },
    { name: "Raatchasan", genre: "Action" },
    { name: "Gangs of Wasseypur", genre: "Action" },
    { name: "Chupke Chupke", genre: "Comedy" },
    { name: "Drishyam", genre: "Crime" },
    { name: "Peranbu", genre: "Drama" },
    { name: "Bangalore Days", genre: "Comedy" },
    { name: "Satya", genre: "Action" },
    { name: "Mahanati", genre: "Biography" },
    { name: "Agent Sai Srinivasa Athreya", genre: "Comedy" },
    { name: "Premam", genre: "Comedy" },
    { name: "Devasuram", genre: "Action" },
    { name: "Super Deluxe", genre: "Comedy" },
    { name: "Bhaag Milkha Bhaag", genre: "Biography" },
    { name: "Tumbbad", genre: "Drama" },
    { name: "Andhadhun", genre: "Crime" },
    { name: "Vikram Vedha", genre: "Action" },
    { name: "Chhichhore", genre: "Comedy" },
    { name: "Chithram", genre: "Comedy" },
    { name: "Zindagi Na Milegi Dobara", genre: "Comedy" },
    { name: "Vikram", genre: "Action" },
    { name: "Guide", genre: "Drama" },
    { name: "Sairat", genre: "Drama" },
    { name: "Kannathil Muthamittal", genre: "Action" },
    { name: "Shahid", genre: "Biography" },
    { name: "Swades", genre: "Drama" },
    { name: "Iruvar", genre: "Biography" },
    { name: "Munna Bhai M.B.B.S.", genre: "Comedy" },
    { name: "Aruvi", genre: "Drama" },
    { name: "Paan Singh Tomar", genre: "Action" },
    { name: "Hera Pheri", genre: "Action" },
    { name: "Spadikam", genre: "Action" },
    { name: "Uri: The Surgical Strike", genre: "Action" },
    { name: "Let's Go! India", genre: "Drama" },
    { name: "Thirst", genre: "Drama" },
    { name: "Mudhalvan", genre: "Action" },
    { name: "Papanasam", genre: "Crime" },
    { name: "Black", genre: "Drama" },
    { name: "Jo Jeeta Wohi Sikandar", genre: "Comedy" },
    { name: "Pudhu Pettai", genre: "Action" },
    { name: "Mandela", genre: "Comedy" },
    { name: "Lagaan: Once Upon a Time in India", genre: "Drama" },
    { name: "PK", genre: "Comedy" },
    { name: "Dhuruvangal Pathinaaru", genre: "Crime" },
    { name: "Sholay", genre: "Action" },
    { name: "Drishyam 2", genre: "Crime" },
    { name: "Soodhu Kavvum", genre: "Comedy" },
    { name: "Talvar", genre: "Crime" },
    { name: "Queen", genre: "Adventure" },
    { name: "Sarfarosh", genre: "Action" },
    { name: "Udaan", genre: "Drama" },
    { name: "Article 15", genre: "Crime" },
    { name: "OMG: Oh My God!", genre: "Comedy" },
    { name: "Barfi!", genre: "Comedy" },
    { name: "Jigarthanda", genre: "Action" },
    { name: "Jana Gana Mana", genre: "Crime" },
    { name: "Theeran Adhigaram Ondru", genre: "Action" },
    { name: "The Legend of Bhagat Singh", genre: "Action" },
    { name: "Rang De Basanti", genre: "Comedy" },
    { name: "Baahubali 2: The Conclusion", genre: "Action" },
    { name: "Ustad Hotel", genre: "Comedy" },
    { name: "Kaakkaa Muttai", genre: "Comedy" },
    { name: "Angoor", genre: "Comedy" },
    { name: "Maheshinte Prathikaaram", genre: "Comedy" },
    { name: "Virumandi", genre: "Action" },
    { name: "Kahaani", genre: "Mystery" },
    { name: "Dil Chahta Hai", genre: "Comedy" },
    { name: "A Wednesday", genre: "Action" },
    { name: "Baasha", genre: "Action" },
    { name: "Masaan", genre: "Drama" },
    { name: "Shershaah", genre: "Action" },
    { name: "Carry On, Munna Bhai", genre: "Comedy" },
    { name: "2018", genre: "Action" },
    { name: "Iqbal", genre: "Drama" },
    { name: "Pithamagan", genre: "Action" },
    { name: "Lucia", genre: "Drama" },
    { name: "Kaun Pravin Tambe?", genre: "Biography" },
    { name: "Pink", genre: "Crime" },
    { name: "Anand", genre: "Drama" },
    { name: "Nil Battey Sannata", genre: "Drama" },
    { name: "Roja", genre: "Drama" },
    { name: "Bajrangi Bhaijaan", genre: "Action" },
    { name: "Charulata", genre: "Drama" },
    { name: "Alai Payuthey", genre: "Drama" },
    { name: "A Northern Story of Valor", genre: "Drama" },
    { name: "Bommarillu", genre: "Comedy" },
    { name: "Omkara", genre: "Action" },
    { name: "Section 375", genre: "Crime" },
    { name: "Bombay", genre: "Drama" },
    { name: "K.G.F: Chapter 1", genre: "Action" },
    { name: "Kantara", genre: "Action" },
    { name: "Indian", genre: "Action" },
    { name: "Rangasthalam 1985", genre: "Action" },
    { name: "Dilwale Dulhania Le Jayenge", genre: "Drama" },
    { name: "Haider", genre: "Action" },
    { name: "Andaz Apna Apna", genre: "Action" },
    { name: "Mughal-E-Azam", genre: "Drama" },
    { name: "Athadu", genre: "Action" },
    { name: "The Great Indian Kitchen", genre: "Comedy" },
    { name: "Special 26", genre: "Crime" },
    { name: "Vaaranam Aayiram", genre: "Action" },
    { name: "Maanaadu", genre: "Action" },
    { name: "Maqbool", genre: "Crime" },
    { name: "Thadam", genre: "Action" },
    { name: "Padaiyappa", genre: "Action" },
    { name: "Gulaal", genre: "Crime" },
    { name: "Ulidavaru Kandanthe", genre: "Crime" },
    { name: "Pelli Choopulu", genre: "Comedy" },
    { name: "K.G.F: Chapter 2", genre: "Action" },
    { name: "Vaastav: The Reality", genre: "Action" },
    { name: "Deewaar", genre: "Action" },
    { name: "Viduthalai: Part 1", genre: "Action" },
    { name: "Company", genre: "Action" },
    { name: "Ugly", genre: "Crime" },
    { name: "Naduvula Konjam Pakkatha Kaanom", genre: "Comedy" },
    { name: "Padosan", genre: "Comedy" },
    { name: "Badhaai Ho", genre: "Comedy" },
    { name: "Aadukalam", genre: "Action" },
    { name: "Kshanam", genre: "Mystery" },
    { name: "Gully Boy", genre: "Drama" },
    { name: "Nayattu", genre: "Crime" },
    { name: "Evaru", genre: "Crime" },
    { name: "My Name Is Khan", genre: "Adventure" },
    { name: "Maanagaram", genre: "Action" },
    { name: "Pranchiyettan and the Saint", genre: "Comedy" },
    { name: "Dev.D", genre: "Comedy" },
    { name: "Sirf Ek Bandaa Kaafi Hai", genre: "Drama" },
    { name: "22 Shey Shraban", genre: "Action" },
    { name: "Kal Ho Naa Ho", genre: "Comedy" },
    { name: "Major", genre: "Action" },
    { name: "Garuda Gamana Vrishabha Vahana", genre: "Crime" },
    { name: "Ayyappanum Koshiyum", genre: "Action" },
    { name: "Thondi Muthalum Driksakshiyum", genre: "Crime" },
    { name: "Jab We Met", genre: "Comedy" },
    { name: "M.S", genre: "Biography" },
    { name: "Ship of Theseus", genre: "Drama" },
    { name: "Charlie", genre: "Adventure" },
    { name: "Manjhi: The Mountain Man", genre: "Biography" },
    { name: "Take Off", genre: "Action" },
    { name: "Deiva Thirumagal", genre: "Drama" },
    { name: "The Brawler", genre: "Action" },
    { name: "Border", genre: "Action" },
    { name: "Vedam", genre: "Action" },
    { name: "Dil Bechara", genre: "Comedy" },
    { name: "Baahubali: The Beginning", genre: "Action" },
    { name: "Salaam Bombay!", genre: "Crime" },
    { name: "Gargi", genre: "Drama" },
    { name: "Karnan", genre: "Action" },
    { name: "Arjun Reddy", genre: "Action" },
    { name: "Pad Man", genre: "Comedy" },
    { name: "Kirik Party", genre: "Comedy" },
    { name: "Vinnaithaandi Varuvaayaa", genre: "Drama" },
    { name: "Baby", genre: "Action" },
    { name: "Super 30", genre: "Biography" },
    { name: "Hridayam", genre: "Drama" },
    { name: "Pizza", genre: "Horror" },
    { name: "Malik", genre: "Action" },
    { name: "Ankhon Dekhi", genre: "Comedy" },
    { name: "The Tashkent Files", genre: "Drama" },
    { name: "The Music Room", genre: "Drama" },
    { name: "Android Kunjappan Ver 5.25", genre: "Comedy" },
    { name: "Hindi Medium", genre: "Comedy" },
    { name: "Love Today", genre: "Comedy" },
    { name: "English Vinglish", genre: "Comedy" },
    { name: "Memories", genre: "Mystery" },
    { name: "Joseph", genre: "Crime" },
    { name: "Hey Ram", genre: "Crime" },
    { name: "Dor", genre: "Drama" },
    { name: "Lakshya", genre: "Action" },
    { name: "Johnny Gaddaar", genre: "Crime" },
    { name: "Airlift", genre: "Action" },
    { name: "Anjaam Pathiraa", genre: "Crime" },
    { name: "Thuppakki", genre: "Action" },
    { name: "Okkadu", genre: "Action" },
    { name: "Ghilli", genre: "Action" },
    { name: "Pokiri", genre: "Action" },
    { name: "Gangaajal", genre: "Action" },
    { name: "Kaakha..Kaakha: The Police", genre: "Action" },
    { name: "The Lunchbox", genre: "Drama" },
    { name: "Vettaiyaadu Vilaiyaadu", genre: "Action" },
    { name: "RRR", genre: "Action" },
    { name: "Kaththi", genre: "Action" },
    { name: "Mumbai Police", genre: "Crime" },
    { name: "Ab Tak Chhappan", genre: "Crime" },
    { name: "Manam", genre: "Comedy" },
    { name: "Oopiri", genre: "Comedy" },
    { name: "Veer-Zaara", genre: "Drama" },
    { name: "Unnaipol Oruvan", genre: "Action" },
    { name: "RangiTaranga", genre: "Mystery" },
    { name: "Vicky Donor", genre: "Comedy" },
    { name: "Thulladha Manamum Thullum", genre: "Drama" },
    { name: "Angamaly Diaries", genre: "Action" },
    { name: "Hazaaron Khwaishein Aisi", genre: "Drama" },
    { name: "Mother India", genre: "Action" },
    { name: "Ayirathil Oruvan", genre: "Action" },
    { name: "Sonchiriya", genre: "Action" },
    { name: "Stanley Ka Dabba", genre: "Comedy" },
    { name: "Secret Superstar", genre: "Drama" },
    { name: "Nayak: The Real Hero", genre: "Action" },
    { name: "Udta Punjab", genre: "Action" },
    { name: "Rock On!!", genre: "Drama" },
    { name: "Mr", genre: "Action" },
    { name: "Mimi", genre: "Comedy" },
    { name: "Happy Days", genre: "Drama" },
    { name: "Badla", genre: "Crime" },
    { name: "Kai Po Che", genre: "Drama" },
    { name: "Poove Unakkaga", genre: "Comedy" },
    { name: "Raazi", genre: "Action" },
    { name: "Dasvidaniya", genre: "Comedy" },
    { name: "Dia", genre: "Drama" }
];

function getRecommendations() {
    const genreSelect = document.getElementById("genreSelect");
    const selectedGenre = genreSelect.value;
    const recommendationsDiv = document.getElementById("recommendations");
    recommendationsDiv.innerHTML = "";

    if (selectedGenre) {
        const recommendedMovies = movies.filter(m => m.genre === selectedGenre);

        if (recommendedMovies.length > 0) {
            let recommendationsHTML = "<h2>Recommended Movies:</h2><ul>";
            recommendedMovies.forEach(m => {
                recommendationsHTML += `<li>${m.name}</li>`;
            });
            recommendationsHTML += "</ul>";
            recommendationsDiv.innerHTML = recommendationsHTML;
        } else {
            recommendationsDiv.innerHTML = "<p>No recommendations found for this genre.</p>";
        }
    } else {
        recommendationsDiv.innerHTML = "<p>Please select a genre.</p>";
    }
}

function getRandomMovie() {
    const recommendationsDiv = document.getElementById("recommendations");
    const randomIndex = Math.floor(Math.random() * movies.length);
    const randomMovie = movies[randomIndex];
    recommendationsDiv.innerHTML = `<h2>Random Movie:</h2><p>${randomMovie.name} (${randomMovie.genre})</p>`;
}
